# Generated by Django 2.0.7 on 2019-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='skip',
            field=models.BooleanField(default=True, verbose_name='Skipped'),
        ),
    ]
