# Generated by Django 2.0.7 on 2019-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_answer_skip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='skip',
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
